name: navy
description: A group of common used utilities and function type definitions for Dart.
version: 1.0.3
homepage: www.theyellowfactory.com


environment:
  sdk: ">=2.17.0 <3.0.0" 

#dependencies:
#  path: ^1.7.0

dev_dependencies:
  flutter_lints: ^2.0.1
  test: ^1.16.5
