name: navy
description: A group of common used utilities and function type definitions for Dart.
version: 1.0.2
author: The Yellow Factory
homepage: www.theyellowfactory.com


environment:
  sdk: ">=2.12.0 <3.0.0"

#dependencies:
#  path: ^1.7.0

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.5
