name: navy
description: A group of common used utilities and function type definitions for Dart.
version: 1.0.3
homepage: www.theyellowfactory.com


environment:
  sdk: ">=3.6.0 <4.0.0" 

#dependencies:
#  path: ^1.7.0

dev_dependencies:
  flutter_lints: ^5.0.0
  test: ^1.25.11
